C++/CharFrequency.cpp, CONTRIBUTORS.md
Hello! I am new to all of this so please let me know if I made any mistakes/missed something.
P.S how do I add people as reviewers?
=> Added a cpp program to find frequency of characters in a word

C++/rat_in_maze.cpp, CONTRIBUTORS.md
#Added rat in a maze program written in C++ 
#Added my name in Contributions.md
Thankyou soo much mam for giving me the opportunity to contribute to open source as this was my first time  contributing.
=> Made changes in C++ and Contributions

CONTRIBUTORS.md, Java/TriplyLinkedList.java
Created TriplyLinkedList.java file in Java folder by SanketJ29
=> Create TriplyLinkedList.java 

CONTRIBUTORS.md, Python/palindrome_number.py
A basic program that check if the number is palindrome or not.
=> palindrome number checker

CONTRIBUTORS.md, Java/BinarySearch.java
Add Binary Search algorithm in Java
=> Java binary search

C/BinarySearch.c
This pull request is linked to the issue #34
=> Created Binary Search Code in C language

C/LinearSearch.c
Kindly merge this pull request regarding the issue : #36
=> Created Linear Search Code in C language

CONTRIBUTORS.md, Java/OrderAgnosticBinarySearch.java
Add order agnostic binary search algorithm in Java
=> Java order agnostic binary search

C++/array.cpp, Java/RotatedBinarySearch.java
Add Rotated Binary Search algorithm in Java
=> Add Rotated Binary Search

CONTRIBUTORS.md, Golang/CheckEmail.go
simple checker email write in golang.. how to run? go run check <email>
=> create checker email

CONTRIBUTORS.md, Python/client1.py, Python/server1.py
Added two new socket programming codes in the python folder and also added my to the CONTRIBUTORS.md file
=> Dishant contribution

Java/SearchInMountainArray.java
Add algorithm for searching in a mountain array in Java
=> Add algorithm for searching in a mountain array

CONTRIBUTORS.md, Java/CheckDays.java
Here I am using array index number to display the day name.
=> Determining Name of the Day

CONTRIBUTORS.md, Java/Tower_Of_Hanoi.java
Thank you for this opportunity.(Like the repository)
=> Add Tower_Of_Hanoi program

C/Avl_tree.c, CONTRIBUTORS.md
I have written the code for AVL Tree operations in C , e.g. Insertion, deletion, left and right rotation
Do check it out and merge it !!
=> C program for Avl tree operations

Java/MagicNumberChecking.java
Added java program to Check Magic Number. 
Do check it out and merge it
=> Added java program to Check Magic Number

Java/RecursiveBinarySearch.java
=> Added Java code for Recursive Binary Search

C/AllTreeOperation.c, Java/RecursiveBinarySearch.java
PS do check it out and merge it. Here I have written a C program to do all Tree operations, a menu driven program
=> Added a Full Menu Driven C program to do all kind of tree operation

CONTRIBUTORS.md, Python/Sieve_of_Eratosthenes.py
Python program to get prime number using Sieve of Eratosthenes
=> Added Sieve_of_Eratosthenes.py

CONTRIBUTORS.md, Javascript/learn_forEach_map.js
Fixed issue #75 and also added some new files under javascript dir
=> fixed issue #75 and added some new files

CONTRIBUTORS.md, Java/swap.java, Javascript/learn_forEach_map.js
The code to perform swapping is present in this PR
=> Added swap in java

CONTRIBUTORS.md, Java/swap.java, Javascript/learn_forEach_map.js, Python/Template_For_FastApi.py
This PR contains the basic template for FastAPI integration
=> Add template for FastAPI integration 

C++/power.cpp
A C++ program to find the power of a number using bit manipulation.
=> Add program to find power of number without pow function

CONTRIBUTORS.md, Java/ticTacToe.java
Added a code written in pure java for the tic-tac-toe game.
=> added Tic-tac-toe in pure java

Python/favicon-hash-generator
Used for finding quick bounties when a new zeroday or a cve is found
=> Created a favicon hash generator

CONTRIBUTORS.md, Kotlin/Arithmetic.kt, Kotlin/Circle.kt, Kotlin/Classes.kt, Kotlin/CustomTriple.kt, Kotlin/Exceptions.kt, Kotlin/ExtenstionFunctions.kt, Kotlin/Functions.kt, Kotlin/ImportantNumbers.kt, Kotlin/LambdaFunctions.kt, Kotlin/Loop.kt, Kotlin/Main.kt, Kotlin/Rectangle.kt, Kotlin/Shape.kt, Kotlin/Strings.kt, Kotlin/When.kt
Added code for kotlin basics, so one can get the reference to learn kotlin
=> added code for kotlin basics

CONTRIBUTORS.md, Java/Quicksort.java
I have added this algo in java please merge this pr
@CODING-Enthusiast9857
=> algo quick sort

C++/Queue_using_Array.cpp, C++/Stack_using_Array.cpp
Closes #100 
Kindly check i had added both the working programs please mention it under hacktoberfest-accepted.
=> Added Stack and Queue in cpp programs

CONTRIBUTORS.md, Python/Egg_catcher.py
@CODING-Enthusiast9857  Hey i added a egg_catcher game so please considered this for my HACKTOBERFEST-2022 PR
=> HACKTOBERFEST-2022

C++/HeapSort.cpp
Added Heap Sort in C++ Programs
=> Add Heap Sort
